# Generated by Django 4.1.1 on 2022-09-18 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FLDjangoServer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='table1',
            options={'managed': False},
        ),
    ]
