# Generated by Django 4.1.1 on 2022-09-18 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FLDjangoServer', '0002_alter_table1_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='table1',
            table='table1',
        ),
    ]
